sudo: false
language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
#  - os: linux
#    compiler: gcc
#    addons:
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        packages:
#          - libboost1.55-all-dev
#          - libssl-dev
#          - g++-7
#          - gcc-7
#    env:
#    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#    - LABEL="linux-g++-7"
#    - STRIP="strip"

  # Ubuntu, clang-6
#  - os: linux
#    compiler: clang
#    addons:
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - llvm-toolchain-trusty-6.0
#        packages:
#          - libboost1.55-all-dev
#          - libssl-dev
#          - clang-6.0
#          - libstdc++-7-dev
#    env:
#    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
#    - LABEL="linux-clang-6"
#    - STRIP="strip"

  ## OSX, g++-8
#  - os: osx
##    osx_image: xcode10
#    compiler: gcc
#    env:
#    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
#    - LABEL="osx-g++-8"
#    - STRIP="strip"

  # OSX, g++-7
#  - os: osx
#    osx_image: xcode10
#    compiler: gcc
#    env:
#    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#    - LABEL="osx-g++-7"
#    - STRIP="strip"

  # OSX, clang
#  - os: osx
#    osx_image: xcode10
#    compiler: clang
#    env:
#    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
#    - LABEL="osx"
#    - _DEPLOYABLE="true"
#    - STRIP="strip"

  # Arm (aarch64) cross compile
#  - os: linux
#    env:
#    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
#    - LABEL="aarch64"
#    - _DEPLOYABLE="true"
#    - STRIP="aarch64-linux-gnu-strip"

#before_install:
#- eval $MATRIX_EVAL

install:
# Need to uninstall oclint to get newer gcc installed https://github.com/travis-ci/travis-ci/issues/8826
#- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true ; fi

# Need a newer version of llvm to link against to get std::filesystem / std::experimental::filesystem
#- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry brew upgrade llvm ; fi

# Need to make sure that we have openssl installed
#- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry brew upgrade openssl ; fi#
#- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
#- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl /usr/local/include ; fi

# Neeed to install ccache
#- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
#- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi

# Install the correct gcc version
#- if [[ "$LABEL" == "osx-g++-8" ]]; then travis_retry brew install gcc@8 ; fi
#- if [[ "$LABEL" == "osx-g++-7" ]]; then travis_retry brew install gcc@7 ; fi

script:
#- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
#- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="UniBitXd miner uniwallet uni-service uniwallet-beta cryptotest wallet-api"
- ${STRIP} ${TARGETS}
- rm -rf yt-${TRAVIS_TAG}
- mkdir yt-${TRAVIS_TAG}
- cp ${TARGETS} yt-${TRAVIS_TAG}/
- cp ../../LICENSE yt-${TRAVIS_TAG}/
- tar cvfz yt-${TRAVIS_TAG}-${LABEL}.tar.gz yt-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp yt-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..
#
deploy:
  - provider: releases
    user: "roy.hodge@mail.com"
    password: "S1mpl3p4ss"
    file:
      - yt-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    on:
      repo: royhodge/yt
      tags: true
      condition: "$_DEPLOYABLE = true"
#
#  - provider: s3
#    access_key_id:
#      secure: DBwV4byu9+n8ZgIg/ncZBlAKAVrhYe4ozCgIk8oxd4ow4sxvyQ7bmUsRKmBwjmRskStu60xVl2OYHU5rK1fc07a8MC/68jhaa1H3qqwaoowFskDF5PW6LVQEu7VlHJqszI821I/m2vDQhXw87RDP6hIqlsXAth6SNUQvr2xGn3GYG8zgUOURVbjU7fbi2q1dvS2Q5Tx7qZ38q+DxV/5raoQRdccWhk0R7xvsTMC3LkeTc8XF7HrYw+n6/tF5fkx3Vnp3MJNZtqBvljNVxbFcHUHvuwKIhDZXpurUQwWarrxQ9YB2Wm+622EZq0UnJP+N56+qYP+A035MIDuTx7Lf6mkNR0I+cDaU0ywM5avm0oXvgfDVQwFTYCwhkMtmrHsISfkFjIZCp8ZAsGEm/rdwlwUP8Mk9kGAFMJuCfEOK5vAyMiKasXEEGFcYxvD92HQPMIjizGyYBdw0BwjgVut48dLFM3VlDlN8GvGoVXllsv0UfepW5JkJWT9XBuF2T+M74U0X/f+E+g6whLRVGZ0tjSzhga9wTKfP0QyWdxzu9U8kJDaYt9Gvca0Xt8VFCT8s9ij0XsNOtOYUo/DQmCn5/okGsVVXgT5KRUt462gJ7IZUX3Ti09KgdQsFfAu2BllaPLvqmu62FwhFdYmkfL9fWgzfE5F2A6HZbV2Di63dew4=
#    secret_access_key:
#      secure: cmy8eYUr8Hpii10a5fsTzhsBT5YNrQp5DCqaGCl6Ebd4T7t4+DpaHbERSUWjM6JCt9z1nmipT976ViJrnWUCBIxhxS/GAKbLPSSXxe6L7mA97ucwTLsICxZaWYjG/PkZl/7bIXH9GIslkxU/490ghciAk9AjNNjkX2jVt/62JOQiuzQomQvwg++3ececI3SfNKm+pNtL789no309PoEuyFewD0C/g15rsOvNoAZqNREcrSOPYJQXph4KWda/hBSWKIHU+kOKWUcdQQBKOchAoJQGJIFRwj4dDhuUwqb9Fz9DSdu6vyujNAOicUxKmrWV2KTNC2mGVK7Oa7dH2oDWV4WcBpI50bZDYghE4e4lz14mV3xkeuQaGGVF21d63jPxEzbXsLwObKtjx+dNqXpFWaVwyGflEkddvLIyqFd8CUtI45kTAHuoeQg0uRG/ols09AfW5iezHkOI50XxWZLZUwfrScTix0vSRwguHRCEnSolIylu36zMg8+azfmKY/aqLt1XidHGDtDjvNvoWZkKimlhC1thGXqzB+e86sTjs3ETdWuaiM/Pi6zJGcLVEnd7hxF98yxQVpJ4zJZzc5Lrc1yomRWkxgWpM+2dHfUomIYj+WSdsJw3YlNmDFL6Ymizw483FBUhStF0BCSSDafC1YatIx5XRUEoElzMz0zIczs=
#    bucket: yt
#    skip_cleanup: true
#    acl: public_read
#    region: us-east-2
#    upload-dir: yt
#    local-dir: src/builds
#    on:
#      repo: royhodge/yt
#      all_branches: true
